spring.application.name=buildmyschema
string.test=${STRING_TEST}
server.port=${PORT:8080}

react.app.url=${REACT_APP_URL}

logging.level.org.springframework.ai.chat.client.advisor=DEBUG
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-5.4-nano
spring.ai.openai.chat.options.max-completion-tokens=16384
spring.ai.openai.embedding.options.model=text-embedding-3-small
spring.mongodb.uri=mongodb+srv://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@dbmscluster.jln8a2h.mongodb.net/?appName=${MONGODB_DATABASE_NAME}
spring.mongodb.database=dbms_architect
spring.data.ai.vectorstore.mongodb.initialize-schema=true
spring.data.ai.vectorstore.mongodb.collection-name=vector_store
spring.data.ai.vectorstore.mongodb.index-name=vector_index
spring.data.ai.vectorstore.mongodb.path-name=embedding
spring.data.mongodb.auto-index-creation=true

spring.data.redis.host=polite-katydid-124061.upstash.io
spring.data.redis.port=6379
spring.data.redis.username=default
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.ssl.enabled=true