spring.application.name=buildmyschema
string.test=${STRING_TEST}
# configure maria db
spring.datasource.url=jdbc:mariadb://localhost:3330/spring_ai
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

#configure open ai model
spring.ai.openai.api-key=${OPENAI_API_KEY}
# Chat model
spring.ai.openai.chat.options.model=gpt-5
# Embedding model (optional)
spring.ai.openai.embedding.options.model=text-embedding-3-small